inherit_from:
  - .rubocop_todo.yml
  - .rubocop_base.yml

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: disable
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - ".ruby-version"
    - "Dockerfile"
    - "Gemfile.lock"
