# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "CI Test Suite"
run-name: 'Test suite'

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  RAILS_ENV: test
  RUBY_VERSION: 3.2.2

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_ignore: |
            .github/**
            Dockerfile
            Gemfile.lock
            .ruby-version
            .rubocop.yml
            .rubocop_todo.yml
            .rubocop_base.yml
      - name: List all changed files
        run: |
          if [ ${{ steps.changed-files.outputs.all_changed_files_count }} -eq 0 ]; then
            echo "No changed files"
          else
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "$file was changed"
            done
          fi
      - name: Rubocop
        run: |
          if [ ${{ steps.changed-files.outputs.all_changed_files_count }} -eq 0 ]; then
            echo "Skipped"
          else
            bundle exec rubocop ${{ steps.changed-files.outputs.all_changed_files }} --parallel
          fi
  test:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    needs:
      - rubocop

    env:
      DB_HOST: localhost
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: ${{ env.DB_PASSWORD }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Set up database schema
        run:
          bundle exec rake db:create db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rspec
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: ${{ env.RUBY_VERSION }}
  #         bundler-cache: true
  #     # Add or replace any other lints here
  #     - name: Security audit dependencies
  #       run: bin/bundler-audit --update
  #     - name: Security audit application code
  #       run: bin/brakeman -q -w2
